### ISSUE TITLE
How to use batchify classifier-free guidance?

### ISSUE THREAD

**Issue by ThisisBillhe** [baaivision/Emu3#56]
Hi! Thanks for your great work! 

The UnbatchedClassifierFreeGuidanceLogitsProcessor Emu3 used greatly slows down the generation efficiency, as model has to forward twice to generate a token. I try to modify the code to use batchify ClassifierFreeGuidanceLogitsProcessor, using padding tokens to align the length of POSITIVE_PROMPT and NEGATIVE_PROMPT. However, the image quality degrades. Do you have any suggestion?

**Comment by nguyentr17** [comment]
Hi @ThisisBillhe , how did you end up fixing this issue?
